FROM almalinux
#CMD ["ping", "-c5","google.com"]
CMD ["google.com"]
ENTRYPOINT ["ping", "-c5",]
#docker run entry:v2 ping -c2 facebook.com (if we override like this in cmd it will work, if we overide like this in the entry point it will 
#not override we will get a error)
